site_name: JAHS-Bench-201 Documentation
docs_dir: docs
repo_url: https://github.com/automl/jahs_bench_201
repo_name: automl/jahs_bench_201
edit_uri: ""
theme:
  name: material
  icon:
    repo: fontawesome/brands/github

nav:
  - Introduction: "README.md"
  - Using the Benchmark: "usage.md"
  - Downloading the Performance Dataset: "download_dataset.md"
  - Downloading the Surrogate Models: "download_surrogate.md"
  - Evaluation Protocol: "evaluation_protocol.md"
  - Analysis of Performance Dataset: "performance_dataset.md"
  - Creation of Surrogate Benchmarks: "surrogate.md"

# extra:
#  version:
#    provider: mike
