site_name: JAHS-Bench-201 Documentation
docs_dir: docs
repo_url: https://github.com/automl/jahs_bench_201
repo_name: automl/jahs_bench_201
edit_uri: ""
theme:
  name: material
  icon:
    repo: fontawesome/brands/github


# extra:
#  version:
#    provider: mike
